version: '3.9'

services:
  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      interval: 20s
      timeout: 10s
      retries: 10

  config-server:
    build: ./danipa-config-server
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=${CONFIG_BACKEND:-native}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${CONFIG_GIT_URI:-}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=${CONFIG_DEFAULT_LABEL:-main}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${CONFIG_USER:-}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${CONFIG_PASS:-}
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,refresh,busrefresh,env
    ports:
      - "${CONFIG_PORT:-8888}:8888"
    volumes:
      - ./config-repo:/config-repo
    depends_on:
      kafka:
        condition: service_healthy

  eureka-server:
    build: ./danipa-eureka-server
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "${EUREKA_PORT:-8761}:8761"
    depends_on:
      config-server:
        condition: service_started

  redis:
    image: redis:7.4.5
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fintech-service:
    build: ./danipa-fintech-service
    container_name: fintech-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_REDIS_HOST=redis
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,refresh,busrefresh,env
    ports:
      - "${FINTECH_PORT:-8080}:8080"
    depends_on:
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      redis:
        condition: service_healthy
